name: "Backend-Depolyment"

on: 
   push:
      branches: ["main"]
      paths:  
      - "backend/**"


jobs:
  CD-deployment:
     runs-on: ubuntu-latest

     steps:
       - name: "Checkout the code"
         uses: actions/checkout@v4
       - run: pwd 

       
       - name: "Configuration to the Aws"
         uses: aws-actions/configure-aws-credentials@v4
         with:
                aws-access-key-id: ${{secrets.AWS_ACCES_KEY}}
                aws-secret-access-key: ${{ secrets.AWS_SECERTE_KEY }}
                aws-region: ${{secrets.AWS_REGION}}

       - name: "SSh to the Ec2"
         uses: appleboy/ssh-action@v1
         with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}   
            port: 22
            debug: true
            script: | 
               sudo chown -R ec2-user:ec2-user /home/ec2-user/web_deplyment_Aws
               git config --global --add safe.directory /home/ec2-user/web_deplyment_Aws
               cd /home/ec2-user/web_deplyment_Aws/
               git pull
               cd backend
               npm i
               npx prisma migrate deploy
               npx prisma generate
               pm2 restart server || pm2 start server.js --name server
        

          

