name: "Frontend-Depolyment"

on:
    push:
        branches: ["main"]
        paths:
           - "frontend/**"



jobs:
    Frontend:
        runs-on: ubuntu-latest
        
        steps:

           - uses: actions/checkout@v4
             

            
           - name: "Install the Node"
             uses: actions/setup-node@v4
             with:
                node-version: 18
             

           - name: "Unit Test"
             run: cd frontend && npm i

           - name: "Build"
             run: 
              cd frontend && npm run build

           - name: "Upload build file"
             uses: actions/upload-artifact@v4
             with:
                name: "Build File"
                path: dist/

    Deploy-in-S3:

        runs-on: ubuntu-lastest
        needs: Frontend

        steps:

            - name: "Download the folder"
              uses: action/download-artifact@v4
              with:
                name: "Build File"

            - run: pwd


            - name: "Configuration to the Aws"
              uses: aws-actions/configure-aws-credentails@v4
              with:
                aws-access-key-id: ${{secrets.AWS_ACCES_KEY}}
                aws-secret-access-key: ${{ secrets.AWS_SECERET_KEY }}
                aws-region: ${{secrets.Aws_REGION}}


            - name: "Upload to the s3"
              run: aws s3 sync . s3://${{secrets.Aws_s3}}

    Deploy-to-Cloudfront:

       runs-on: ubuntu-lastest
       needs: Deploy-in-S3

       steps:

           - name: "Configuration to the Aws"
             uses: aws-action/configure-aws-credentails@v4
             with:
                aws-access-key-id: ${{secrets.AWS_ACCES_KEY}}
                aws-secret-access-key: ${{ secrets.AWS_SECERET_KEY }}
                aws-region: ${{secrets.Aws_REGION}}

           - name: "Cloudfront Invalidtion"
             run: aws cloudfront create-invalidation --distribution-id ${{secrets.Aws_CLOUDFRONT}} --paths "/*"
